/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siram.main;

import com.siram.internal.FormBahan;
import com.siram.internal.FormPembelian;
import com.siram.internal.FormPenjualan;
import com.siram.internal.FormProduct;
import com.siram.internal.FormSuplier;
import com.siram.internal.FormUser;
import com.siram.popup.About;
import com.siram.popup.Penjualan;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author BadikIrwan
 */
public class FormMain extends javax.swing.JFrame {
    public String hakakses;
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        aktifMenu();
        loginas.setText("you must login first.");
        setLocationRelativeTo(null);
    }
    
    public JLabel getUserLabel() {
        return txtuser;
    }
    
    public void setMenuLogin() {
        if(hakakses.equals("ADMIN")) {
            Sistem.setEnabled(false);
            Master.setEnabled(true);
            User.setEnabled(true);
            Laporan.setEnabled(true);
        } else if(hakakses.equals("KASIR")) {
            Sistem.setEnabled(true);
            Master.setEnabled(false);
            User.setEnabled(false);
        }
    }
    public void aktifMenu() {
        menuLogout.setEnabled(false);
        Sistem.setEnabled(false);
        Master.setEnabled(false);
        User.setEnabled(false);
        Laporan.setEnabled(false);
    }
    
    public void logout() {
        menuLogin.setEnabled(true);
        Sistem.setEnabled(false);
        Master.setEnabled(false);
        User.setEnabled(false);
        Laporan.setEnabled(false);
    }
    public void isLoggin(boolean b) {
        menuLogin.setEnabled(!b);
        menuLogout.setEnabled(b);
        if(b) {
            loginas.setText("Login as : ");
        } else {
            loginas.setText("you must login first.");
            txtuser.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        loginas = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenuItem();
        Sistem = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenuItem();
        menuPembelian = new javax.swing.JMenuItem();
        Master = new javax.swing.JMenu();
        menuBahan = new javax.swing.JMenuItem();
        menuProduk = new javax.swing.JMenuItem();
        menuSuplier = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        User = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Rumah Makan");
        setResizable(false);

        DesktopPane.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        loginas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginas.setText("Login as :");

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtuser)
                .addContainerGap(921, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginas)
                    .addComponent(txtuser))
                .addContainerGap())
        );

        File.setText("File");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        File.add(menuLogin);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        File.add(menuLogout);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        File.add(menuexit);

        jMenuBar1.add(File);

        Sistem.setText("Sistem");

        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        Sistem.add(menuPenjualan);

        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        Sistem.add(menuPembelian);

        jMenuBar1.add(Sistem);

        Master.setText("Master");

        menuBahan.setText("Data Bahan");
        menuBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBahanActionPerformed(evt);
            }
        });
        Master.add(menuBahan);

        menuProduk.setText("Data Produk");
        menuProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdukActionPerformed(evt);
            }
        });
        Master.add(menuProduk);

        menuSuplier.setText("Data Suplier");
        menuSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuplierActionPerformed(evt);
            }
        });
        Master.add(menuSuplier);

        jMenuBar1.add(Master);

        Laporan.setText("Laporan");
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Laporan Stok Bahan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Laporan.add(jMenuItem2);

        jMenuItem4.setText("Laporan Penjualan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Laporan.add(jMenuItem4);

        jMenuBar1.add(Laporan);

        User.setText("User");

        menuUser.setText("Data Users");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        User.add(menuUser);

        jMenuBar1.add(User);

        About.setText("About");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        About.add(menuAbout);

        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DesktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin(null, true, this);
        login.show();
        setLayout(null);
        login.setUndecorated(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBahanActionPerformed
        // TODO add your handling code here:
        FormBahan menubahan = new FormBahan();
        DesktopPane.add(menubahan);
        menubahan.setVisible(true);
        InternalFrameUI ui = menubahan.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menubahan.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuBahanActionPerformed

    private void menuProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdukActionPerformed
        // TODO add your handling code here:
        FormProduct menuproduk = new FormProduct();
        DesktopPane.add(menuproduk);
        menuproduk.setVisible(true);
        InternalFrameUI ui = menuproduk.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menuproduk.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuProdukActionPerformed

    private void menuSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuplierActionPerformed
        // TODO add your handling code here:
        FormSuplier menusuplier = new FormSuplier();
        DesktopPane.add(menusuplier);
        menusuplier.setVisible(true);
        InternalFrameUI ui = menusuplier.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menusuplier.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuSuplierActionPerformed

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        // TODO add your handling code here:
        FormPembelian menupembelian = new FormPembelian();
        DesktopPane.add(menupembelian);
        menupembelian.setVisible(true);
        InternalFrameUI ui = menupembelian.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menupembelian.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        FormPenjualan menupenjualan = new FormPenjualan();
        DesktopPane.add(menupenjualan);
        menupenjualan.setVisible(true);
        InternalFrameUI ui = menupenjualan.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menupenjualan.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        About about = new About(null, true, this);
        about.show();
        setLayout(null);
        about.setUndecorated(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        FormUser menuuser = new FormUser();
        DesktopPane.add(menuuser);
        menuuser.setVisible(true);
        InternalFrameUI ui = menuuser.getUI();
        ((BasicInternalFrameUI)ui).setNorthPane(null);
        try {
            menuuser.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        logout();
        JOptionPane.showMessageDialog(null, "Logout sukses!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        loginas.setText("you must login first.");
        txtuser.setText("");
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuexitActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_LaporanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
            String NamaFile = "/com/siram/report/Laporan_Stok_Bahan.jasper";
            HashMap hash = new HashMap();
        try {
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Penjualan about = new Penjualan(null, true, this);
        about.show();
        setLayout(null);
        about.setUndecorated(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenu Master;
    private javax.swing.JMenu Sistem;
    private javax.swing.JMenu User;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginas;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuBahan;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuProduk;
    private javax.swing.JMenuItem menuSuplier;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenuItem menuexit;
    public javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
