/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siram.internal;

import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author BadikIrwan
 */
public class FormBahan extends javax.swing.JInternalFrame {
    public boolean databaru;
    
    /**
     * Creates new form FormBahan
     */
    public FormBahan() {
        initComponents();
        aktif(false);
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtkodebahan = new javax.swing.JTextField();
        txtnamabahan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();

        setBorder(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/delete.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/exit.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Bahan"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Stok");

        txtstok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Harga");

        txtharga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtkodebahan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtnamabahan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama Bahan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Koder Bahan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Satuan");

        txtsatuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtstok)
                    .addComponent(txtharga)
                    .addComponent(txtnamabahan)
                    .addComponent(txtkodebahan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkodebahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamabahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnsimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/save.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/edit.png"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkeluar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar)
                    .addComponent(btnedit))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        databaru = true;
        aktif(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        Connection con = (Connection)com.siram.koneksi.Koneksi.getKoneksi();
        int baris = tabel.getSelectedRow();
        try {
            Statement st = con.createStatement();
            if(baris == -1) {
                JOptionPane.showMessageDialog(rootPane, "Anda belum memilih tabel");
            } else {
                String sql = "DELETE FROM bahan WHERE kode_bahan='"+tabel.getModel().getValueAt(baris, 0)+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            }
            
        } catch(Exception e) {
            
        }
        kosongkan();
        getData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        try {
            int row =tabel.getSelectedRow();
            String tabel_klik=(tabel.getModel().getValueAt(row, 0).toString());
            Connection con =(Connection)com.siram.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet sql = st.executeQuery("SELECT * FROM bahan WHERE kode_bahan='"+tabel_klik+"'");
            if(sql.next()){
                String kode = sql.getString("kode_bahan");
                txtkodebahan.setText(kode);
                String nama = sql.getString("nama_bahan");
                txtnamabahan.setText(nama);
                String satuan = sql.getString("satuan");
                txtsatuan.setText(satuan);
                String harga = sql.getString("harga");
                txtharga.setText(harga);
                String stok = sql.getString("stok");
                txtstok.setText(stok);
            } 
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String kode = txtkodebahan.getText();
        String nama = txtnamabahan.getText();
        String satuan = txtsatuan.getText();
        String harga = txtharga.getText();
        String stok = txtstok.getText();
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        try {
            if(kode.equals("")||nama.equals("")||harga.equals("")||stok.equals("")) {
                JOptionPane.showMessageDialog(this, "Data ada yang kosong", "pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                Statement st = con.createStatement();
                String sql = "INSERT INTO bahan(kode_bahan,nama_bahan,satuan,harga,stok) VALUES('"+kode+"','"+nama+"',"
                        + "'"+satuan+"','"+harga+"','"+stok+"')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di simpan");
            }
        } catch(SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Data gagal tersimpan", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        kosongkan();
        getData();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        String kode = txtkodebahan.getText();
        String nama = txtnamabahan.getText();
        String satuan = txtsatuan.getText();
        String harga = txtharga.getText();
        String stok = txtstok.getText();
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        try {
            if(kode.equals("")||nama.equals("")||harga.equals("")||stok.equals("")) {
                JOptionPane.showMessageDialog(this, "Data ada yang kosong", "pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                Statement st = con.createStatement();
                String sql = "UPDATE bahan SET kode_bahan='"+kode+"',nama_bahan='"+nama+"',satuan='"+satuan+"',"
                       + "harga='"+harga+"',stok='"+stok+"' WHERE kode_bahan='"+kode+"'"; 
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di diedit");
            } 
            
        } catch(SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Data gagal diedit", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        kosongkan();
        getData();
    }//GEN-LAST:event_btneditActionPerformed

    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    public void kosongkan() {
        txtkodebahan.setText("");
        txtnamabahan.setText("");
        txtsatuan.setText("");
        txtharga.setText("");
        txtstok.setText("");
    }
    
    private void aktif(boolean b) {
        txtkodebahan.setEditable(b);
        txtnamabahan.setEditable(b);
        txtsatuan.setEditable(b);
        txtharga.setEditable(b);
        txtstok.setEditable(b);
    }
    
    private void getData() {
        DefaultTableModel tbm = new DefaultTableModel();
        tbm.addColumn("KODE");
        tbm.addColumn("NAMA BAHAN");
        tbm.addColumn("SATUAN");
        tbm.addColumn("HARGA");
        tbm.addColumn("STOK");
        try {
            Connection con = (Connection)com.siram.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from bahan");
            while(rs.next()) {
                tbm.addRow(new Object[] {
                    rs.getString("kode_bahan"), rs.getString("nama_bahan"), rs.getString("satuan"), rs.getString("harga"),
                    rs.getString("stok")});
               tabel.setModel(tbm);
            }
        } catch(Exception e) {
            
        }
       //AutoSizeTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabel;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkodebahan;
    private javax.swing.JTextField txtnamabahan;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
