/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siram.internal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BadikIrwan
 */
public class FormPembelian extends javax.swing.JInternalFrame {
DefaultTableModel model;
public String tglchooser;
    /**
     * Creates new form FormPembelian
     */
    public FormPembelian() {
        initComponents();
        autokode();
        kode_suplier();
        kode_bahan();
        tabel_transaksi();
        //getData();
       
        //tabel_transaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnotransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnotabeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbsuplier = new javax.swing.JComboBox<>();
        txtnamasuplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cbbahan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtnamabahan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthargabeli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtjumlahbeli = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();

        setBorder(null);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        btnsimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/save.png"))); // NOI18N
        btnsimpan.setText("Simpan ");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/delete.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnkeluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siram/picture/exit.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sub Total");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pembelian"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("No. Transaksi");

        txtnotransaksi.setEditable(false);
        txtnotransaksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nota Beli");

        txtnotabeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Suplier");

        cbsuplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbsuplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cbsuplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsuplierItemStateChanged(evt);
            }
        });

        txtnamasuplier.setEditable(false);
        txtnamasuplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal");

        tanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnotransaksi)
                    .addComponent(txtnotabeli)
                    .addComponent(cbsuplier, 0, 120, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnamasuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtnotransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnotabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbsuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamasuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Kode Bahan");

        cbbahan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cbbahan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbahanItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nama Bahan");

        txtnamabahan.setEditable(false);
        txtnamabahan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Satuan");

        txtsatuan.setEditable(false);
        txtsatuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Harga beli satuan");

        txthargabeli.setEditable(false);
        txthargabeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Jumlah Beli");

        txtjumlahbeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btntambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btntambah.setText("Add item");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbahan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamabahan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txthargabeli)
                                .addComponent(txtjumlahbeli, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addComponent(btntambah))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnkeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtnamabahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntambah)))
                    .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbsuplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsuplierItemStateChanged
        // TODO add your handling code here:
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        ResultSet rs;
        String sql = "SELECT * FROM suplier WHERE kode_suplier = '"+cbsuplier.getSelectedItem().toString()+"'";
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()){
                txtnamasuplier.setText(rs.getString("nama_suplier"));
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbsuplierItemStateChanged

    private void cbbahanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbahanItemStateChanged
        // TODO add your handling code here:
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        ResultSet rs;
        String sql = "SELECT * FROM bahan WHERE kode_bahan = '"+cbbahan.getSelectedItem().toString()+"'";
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()){
                txtnamabahan.setText(rs.getString("nama_bahan"));
                txtsatuan.setText(rs.getString("satuan"));
                txthargabeli.setText(rs.getString("harga"));
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbbahanItemStateChanged

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        if(txtnotabeli.getText().equals("")||txtjumlahbeli.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data tidak boleh kosong");
        }
        else{
            int total = Integer.parseInt(txthargabeli.getText()) * Integer.parseInt(txtjumlahbeli.getText());
            int simpan2 = 0;
            if(txttotal.getText().equals("")){
                simpan2 = 0;
            }
            else
                simpan2 = Integer.valueOf(txttotal.getText());

            String sql = "INSERT INTO item_pembelian(no_transaksi,kode_bahan,nama_bahan,satuan,qty,harga,jumlah) "
                    + "VALUES('"+txtnotransaksi.getText()+"','"+cbbahan.getSelectedItem().toString()+"','"+txtnamabahan.getText()+"',"
                    + "'"+txtsatuan.getText()+"','"+txtjumlahbeli.getText()+"','"+txthargabeli.getText()+"','"+total+"')";
            try {
                    //simpan_no();
                    Statement st = con.createStatement();
                    st.executeUpdate(sql);
                    txttotal.setText(String.valueOf(simpan2+total));
                    //JOptionPane.showMessageDialog(this, "Barang Berhasil Dibeli");
                    tampil_tabel();
                    //tabel_transaksi();
                    //tampil_tabel_transaksi();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        try {
            Statement st = con.createStatement();
            String sql = "INSERT INTO pembelian(no_transaksi,nota_beli,suplier,order_date,harga)"
                    + "VALUES('"+txtnotransaksi.getText()+"','"+txtnotabeli.getText()+"','"+txtnamasuplier.getText()+"',"
                    + "'"+tglchooser+"','"+txttotal.getText()+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Barang Berhasil Disimpan");
        } catch(Exception e) {
           JOptionPane.showMessageDialog(this, "Data gagal tersimpan", "Pesan", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        Connection con = (Connection)com.siram.koneksi.Koneksi.getKoneksi();
        int baris = tabel1.getSelectedRow();
        try {
            Statement st = con.createStatement();
            if(baris == -1) {
                JOptionPane.showMessageDialog(rootPane, "Anda belum memilih tabel");
            } else {
                String sql = "DELETE FROM item_pembelian WHERE no='"+tabel1.getModel().getValueAt(baris, 0)+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
                getData();
            }
            
        } catch(Exception e) {
            
        }
        getData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
        if(tanggal.getDate()!=null) {
           SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
           tglchooser = format.format(tanggal.getDate()); 
        }
    }//GEN-LAST:event_tanggalPropertyChange

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void autokode() {
        try {
            Connection con = com.siram.koneksi.Koneksi.getKoneksi();
            String sql= "SELECT MAX(right(no_transaksi,2)) AS no FROM pembelian";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()) {
                if(rs.first()==false) {
                    txtnotransaksi.setText("PB0000001");
                } else {
                    rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<7-noLong;a++)
                    { 
                        no = "0" + no;
                    }
                   txtnotransaksi.setText("PB" + no);
                }
            }
        } catch (Exception e) {
            
        }
    }
    
    public void kode_suplier(){
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        String sql = "SELECT * FROM suplier";
        try {
         Statement st = con.createStatement();
         ResultSet rs= st.executeQuery(sql);
         while(rs.next()){
             cbsuplier.addItem(rs.getString("kode_suplier"));
         }
        } catch (Exception e) {
        }
    }
    
    public void kode_bahan(){
        Connection con = com.siram.koneksi.Koneksi.getKoneksi();
        String sql = "SELECT * FROM bahan";
        try {
         Statement st = con.createStatement();
         ResultSet rs= st.executeQuery(sql);
         while(rs.next()){
             cbbahan.addItem(rs.getString("kode_bahan"));
         }
        } catch (Exception e) {
        }
    }
    
    private void tabel_transaksi(){
        DefaultTableModel tbm = new DefaultTableModel();
        tbm.addColumn("NOMOR");
        tbm.addColumn("KODE BAHAN");
        tbm.addColumn("NAMA BAHAN");
        tbm.addColumn("SATUAN");
        tbm.addColumn("QTY");
        tbm.addColumn("HARGA");
        tbm.addColumn("TOTAL");
        tabel1.setModel(tbm);
    }
    
     public void tampil_tabel() {
        DefaultTableModel tbm = new DefaultTableModel();
        tbm.addColumn("NOMOR");
        tbm.addColumn("KODE BAHAN");
        tbm.addColumn("NAMA BAHAN");
        tbm.addColumn("SATUAN");
        tbm.addColumn("QTY");
        tbm.addColumn("HARGA");
        tbm.addColumn("TOTAL");
        try {
            Connection con = com.siram.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from item_pembelian WHERE no_transaksi='"+txtnotransaksi.getText()+"'");
            while(rs.next()) {
                tbm.addRow(new Object[] {
                    rs.getString("no"),rs.getString("kode_bahan"), rs.getString("nama_bahan"), rs.getString("satuan"), 
                    rs.getString("qty"), rs.getString("harga"), rs.getString("jumlah")});
               tabel1.setModel(tbm);
            }
        } catch(Exception e) {
            
        }
       //AutoSizeTable();
    }
     
    public void getData() {
        DefaultTableModel tbm = new DefaultTableModel();
        try {
            Connection con = com.siram.koneksi.Koneksi.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from item_pembelian");
            while(rs.next()) {
                tbm.addRow(new Object[] {
                    rs.getString("no"),rs.getString("kode_bahan"), rs.getString("nama_bahan"), rs.getString("satuan"), 
                    rs.getString("qty"), rs.getString("harga"), rs.getString("jumlah")});
               tabel1.setModel(tbm);
            }
        } catch(Exception e) {
            
        }
       //AutoSizeTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cbbahan;
    private javax.swing.JComboBox<String> cbsuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabel1;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtnamabahan;
    private javax.swing.JTextField txtnamasuplier;
    private javax.swing.JTextField txtnotabeli;
    private javax.swing.JTextField txtnotransaksi;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
